import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Bell,
  AlertTriangle,
  Info,
  Clock,
  MessageSquare,
  Calendar,
  User,
  Eye,
  Trash2,
  CheckCircle, // New for "SUCCESS"
} from "lucide-react";
import { useEffect } from "react";

interface NotificationTableProps {
  notifications: any[]; // From hook
  branches: any[]; // New prop for branch lookup
  onView: (id: string) => void;
  onDelete: (id: string) => void;
}

export function NotificationTable({
  notifications,
  branches,
  onView,
  onDelete,
}: NotificationTableProps) {
  const getTypeColor = (type: string): string => {
    switch (type.toLowerCase()) {
      case "emergency":
        return "bg-red-100 text-red-800";
      case "warning":
        return "bg-yellow-100 text-yellow-800";
      case "info":
        return "bg-blue-100 text-blue-800";
      case "reminder":
        return "bg-purple-100 text-purple-800";
      case "alert":
        return "bg-orange-100 text-orange-800";
      case "success": // New for API
        return "bg-green-100 text-green-800";
      default:
        return "bg-gray-100 text-gray-800";
    }
  };

  const getPriorityColor = (priority: string): string => {
    switch (priority.toLowerCase()) {
      case "urgent":
        return "bg-red-100 text-red-800";
      case "high":
        return "bg-orange-100 text-orange-800";
      case "medium":
        return "bg-yellow-100 text-yellow-800";
      case "low":
        return "bg-green-100 text-green-800";
      case "normal": // New for API
        return "bg-gray-100 text-gray-800";
      default:
        return "bg-gray-100 text-gray-800";
    }
  };

  const getStatusColor = (status: string): string => {
    switch (status.toLowerCase()) {
      case "active":
        return "bg-green-100 text-green-800";
      case "scheduled":
        return "bg-blue-100 text-blue-800";
      case "expired":
        return "bg-gray-100 text-gray-800";
      case "draft":
        return "bg-yellow-100 text-yellow-800";
      case "sent": // New for API
        return "bg-blue-100 text-blue-800";
      default:
        return "bg-gray-100 text-gray-800";
    }
  };

  const getTypeIcon = (type: string) => {
    switch (type.toLowerCase()) {
      case "emergency":
        return <AlertTriangle className="h-4 w-4" />;
      case "warning":
        return <AlertTriangle className="h-4 w-4" />;
      case "info":
        return <Info className="h-4 w-4" />;
      case "reminder":
        return <Clock className="h-4 w-4" />;
      case "alert":
        return <Bell className="h-4 w-4" />;
      case "success": // New for API
        return <CheckCircle className="h-4 w-4" />;
      default:
        return <MessageSquare className="h-4 w-4" />;
    }
  };

  useEffect(() => {
    console.log("notificationss", notifications);
  });

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Bell className="h-5 w-5" />
          System Notifications
        </CardTitle>
        <CardDescription>
          Manage and track all system notifications and announcements
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="rounded-md border">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>User</TableHead>
                <TableHead>Notification Details</TableHead>
                <TableHead>Type & Priority</TableHead>
                <TableHead>Schedule & Status</TableHead>
                <TableHead>Generated By</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {notifications.map((notification) => (
                <TableRow key={notification.id} className="text-xs">
                  <TableCell>
                    <div className="space-y-1 font-semibold">
                      {notification?.metadata?.fullName}
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="space-y-1">
                      <div className="font-medium flex items-center gap-2">
                        {getTypeIcon(notification.type)}
                        {notification.title}
                      </div>
                      <div className="text-muted-foreground line-clamp-2">
                        {notification.title === "Early Departure Rejected" ||
                        notification.title === "Early Departure Approved"
                          ? `${
                              notification.metadata.fullName
                            }'s ${notification.title.toLowerCase()}.`
                          : notification.message}
                      </div>
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="space-y-2 flex flex-col gap-1">
                      <div
                        className={`${getTypeColor(
                          notification.type
                        )} rounded-lg w-fit px-3 py-1 text-xs font-semibold`}
                      >
                        {notification.type.charAt(0).toUpperCase() +
                          notification.type.slice(1).toLowerCase()}
                      </div>
                      <div
                        className={`${getPriorityColor(
                          notification.priority
                        )} rounded-lg w-fit px-3 py-1 text-xs font-semibold`}
                      >
                        {notification.priority.charAt(0).toUpperCase() +
                          notification.priority.slice(1).toLowerCase()}
                      </div>
                    </div>
                  </TableCell>

                  <TableCell>
                    <div className="space-y-1">
                      <Badge
                        variant="outline"
                        className={getStatusColor(notification.status)}
                      >
                        {notification.status.charAt(0).toUpperCase() +
                          notification.status.slice(1).toLowerCase()}
                      </Badge>
                      <div className="text-sm text-muted-foreground">
                        <div className="flex items-center">
                          <Calendar className="h-3 w-3 mr-1" />
                          {new Date(
                            notification.metadata.clockInTime ||
                              notification.createdAt
                          ).toLocaleString()}
                        </div>
                        {notification.expiresAt && ( // Optional if present
                          <div className="flex items-center">
                            <Clock className="h-3 w-3 mr-1" />
                            Expires:{" "}
                            {new Date(notification.expiresAt).toLocaleString()}
                          </div>
                        )}
                      </div>
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="space-y-1">
                      <div className="flex items-center text-xs text-muted-foreground">
                        <User className="h-3 w-3 mr-1" />
                        {notification.sender.role}
                      </div>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>

        {notifications.length === 0 && (
          <div className="text-center py-8">
            <Bell className="h-12 w-12 mx-auto mb-4 text-muted-foreground" />
            <h3 className="text-lg font-medium mb-2">No notifications found</h3>
            <p className="text-muted-foreground">
              Try adjusting your search criteria or create a new notification.
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
